; Orca Slicer Sample G-code
; Generated by: Orca Slicer 2.0.0
; estimated printing time = 2h 30m 45s
; filament used [mm] = 12345.67
; filament used [g] = 37.5
; layer_height = 0.2
; total layers count = 150
; nozzle_temperature = 210
; bed_temperature = 60

; Start G-code
G28 ; Home all axes
G1 Z5 F3000 ; Lift nozzle

M104 S210 ; Set nozzle temp
M140 S60 ; Set bed temp
M109 S210 ; Wait for nozzle temp
M190 S60 ; Wait for bed temp

; Layer 1
;LAYER:0
G1 X0 Y0 Z0.2 F3000
G1 E10 F1500
; ... printing commands ...

; Layer 150
;LAYER:149
G1 X100 Y100 Z30.0 F3000
; ... more printing commands ...

; End G-code
M104 S0 ; Turn off nozzle
M140 S0 ; Turn off bed
G28 X Y ; Home X Y
M84 ; Disable motors
